go:
  cgo: false
repository:
  path: .
build:
  binaries:
  - name: clickhouse-exporter
  flags: -a -tags netgo
  ldflags: |
    -s
    -w
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
